mykees_comment_manage:
    pattern:  /manage
    defaults: { _controller: MykeesCommentBundle:Comments:manage }
    requirements:
        bundle: "[a-zA-Z0-9]+"
        ref: "[a-zA-Z0-9]+"
        ref_id:  \d+
