language: php

php:
    - 5.6

env:
    - SYMFONY_VERSION=2.6.*

before_install:
    - composer self-update

before_script:
    - phpenv config-rm xdebug.ini || true
    - mysql -e "create database test;"
    - composer require symfony/symfony:${SYMFONY_VERSION} --no-update
    - composer install
    - travis_wait php Tests/Fixtures/bin/console --env=test doctrine:schema:create
    - travis_wait php Tests/Fixtures/bin/console --env=test doctrine:schema:update --force
    - travis_wait php Tests/Fixtures/bin/console --env=test assetic:dump


after_script:
    - travis_wait php Tests/Fixtures/bin/console --env=test doctrine:database:drop --force

script:
    - phpunit
